# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{textmate}
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Dollar"]
  s.date = %q{2009-09-09}
  s.default_executable = %q{textmate}
  s.description = %q{Command-line package manager for textmate}
  s.email = %q{<ddollar@gmail.com>}
  s.executables = ["textmate"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/textmate",
     "lib/textmate.rb",
     "lib/textmate/local.rb",
     "lib/textmate/remote.rb",
     "lib/textmate/source.rb",
     "lib/textmate/source/base.rb",
     "lib/textmate/source/github.rb",
     "lib/textmate/source/macromates.rb",
     "textmate.gemspec"
  ]
  s.homepage = %q{http://github.com/ddollar/textmate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Command-line package manager for textmate}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0.11.5"])
      s.add_runtime_dependency(%q<fcoury-octopi>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.4.4"])
    else
      s.add_dependency(%q<thor>, [">= 0.11.5"])
      s.add_dependency(%q<fcoury-octopi>, [">= 0.1.0"])
      s.add_dependency(%q<httparty>, [">= 0.4.4"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0.11.5"])
    s.add_dependency(%q<fcoury-octopi>, [">= 0.1.0"])
    s.add_dependency(%q<httparty>, [">= 0.4.4"])
  end
end
